name: fundwise
description: A premium mutual fund CAS parser and portfolio tracker.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0
  file_selector: ^1.0.3
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  flutter_pdf_text: ^0.9.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
